### ISSUE TITLE
Not able to start app - plugin missing?

### ISSUE THREAD

**Issue by nicholasalanbrown** [Differential/meteor-boilerplate#54]
Hello:

I was curious to check this out and just cloned the repo. Upon running "meteor," I get this:

```
W20150311-10:03:54.256(-4)? (STDERR) Error: No plugin found named "ensureSignedIn"
W20150311-10:03:54.256(-4)? (STDERR)     at Function.Router.plugin (packages/iron:router/lib/router.js:394:1)
W20150311-10:03:54.256(-4)? (STDERR)     at app/both/router/routes.js:9:8
W20150311-10:03:54.257(-4)? (STDERR)     at app/both/router/routes.js:13:3
W20150311-10:03:54.257(-4)? (STDERR)     at /Users/nbrown/Source/slideout/.meteor/local/build/programs/server/boot.js:205:10
W20150311-10:03:54.257(-4)? (STDERR)     at Array.forEach (native)
W20150311-10:03:54.257(-4)? (STDERR)     at Function._.each._.forEach (/Users/nbrown/.meteor/packages/meteor-tool/.1.0.40.1gilgv1++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150311-10:03:54.257(-4)? (STDERR)     at /Users/nbrown/Source/slideout/.meteor/local/build/programs/server/boot.js:116:5
```

Any ideas?

**Comment by nickw** [comment]
@bySabi any thoughts on this? Seems to be related to #52

**Comment by bySabi** [comment]
@nicholasalanbrown  please update cloned repository:
`meteor update`
and you get something like this:
```
...
useraccounts:bootstrap     upgraded from 1.4.1 to 1.8.1
useraccounts:core          upgraded from 1.4.1 to 1.8.1
...
```
@nickw we need a PR to set useraccounts:bootstrap to minimun 1.8.1?

**Comment by nickw** [comment]
Ok I just pushed a commit with updated packages. Let me know if that helps.

**Comment by nicholasalanbrown** [comment]
Looks resolved. Thanks!
